# Generated by Django 6.0.3 on 2026-03-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="po_number",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
