# Generated by Django 6.0.3 on 2026-03-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_remove_invoice_po_number_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="confidence_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
